name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. We only want the contents of 'backend' to go to HF
          # 2. This ensures the Dockerfile is in the root of the HF Space
          git subtree push --prefix backend https://Aankit123:$HF_TOKEN@huggingface.co/spaces/Aankit123/talentai-backend main
